USE MASTER
GO

IF EXISTS(SELECT NAME FROM sys.databases WHERE NAME = 'CursuriDansCod') BEGIN
	DROP DATABASE CursuriDansCod
END
GO

CREATE DATABASE CursuriDansCod
GO
USE CursuriDansCod
GO

CREATE TABLE Categorii(
	ID INT PRIMARY KEY,
	denumire VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Coregrafi(
	ID INT,
	nume VARCHAR(50) NOT NULL,
	prenume VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);
GO

CREATE TABLE Locatii(
	ID INT PRIMARY KEY,
	tara VARCHAR(50) NOT NULL,
	judet VARCHAR(50) NOT NULL,
	localitate VARCHAR(50) NOT NULL,
	strada VARCHAR(50) NOT NULL,
	numar INT NOT NULL,
	scara VARCHAR(50),
	apartament VARCHAR(50)
);
GO

CREATE TABLE Pachete(
	ID INT PRIMARY KEY,
	discount INT NOT NULL,
	diploma BIT
);
GO

CREATE TABLE Cursuri(
	ID INT PRIMARY KEY,
	denumire VARCHAR(10) NOT NULL,
	durata FLOAT NOT NULL,
	pret MONEY NOT NULL,
	id_categorie INT CONSTRAINT FK_Cursuri_Categorii FOREIGN KEY REFERENCES Categorii(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	id_pachet INT CONSTRAINT FK_Cursuri_Pachete FOREIGN KEY REFERENCES Pachete(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE Grupe(
	ID INT PRIMARY KEY,
	nivel_minim INT CHECK( nivel_minim>0 AND nivel_minim<11 ) NOT NULL,
	varsta_minima INT NOT NULL,
	id_curs INT NOT NULL CONSTRAINT FK_Grupe_Cursuri FOREIGN KEY REFERENCES Cursuri(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE Elevi(
	ID INT PRIMARY KEY,
	nume VARCHAR(50) NOT NULL,
	prenume VARCHAR(50) NOT NULL,
	data_nasterii DATETIME NOT NULL,
	telefon CHAR(10) NOT NULL,
	id_grupa INT CONSTRAINT FK_Elevi_Grupe FOREIGN KEY REFERENCES Grupe(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE Profesie(
	id_curs INT CONSTRAINT FK_Profesii_Cursuri FOREIGN KEY REFERENCES Cursuri(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	id_coregraf INT CONSTRAINT FK_Profesii_Coregrafi FOREIGN KEY REFERENCES Coregrafi(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(id_curs,id_coregraf)	
);
GO

CREATE TABLE Progrese(
	id_elev INT CONSTRAINT FK_Progrese_Elevi FOREIGN KEY REFERENCES Elevi(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	id_curs INT CONSTRAINT FK_Progrese_Cursuri FOREIGN KEY REFERENCES Cursuri(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	nivel INT CHECK( nivel>0 AND nivel<11 ) NOT NULL,
	PRIMARY KEY(id_elev,id_curs)
);
GO

CREATE TABLE Rasfirare(
	id_curs INT CONSTRAINT FK_Rasfirari_Cursuri FOREIGN KEY REFERENCES Cursuri(ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	id_locatie INT CONSTRAINT FK_Rasfirari_Locatii FOREIGN KEY REFERENCES Locatii(ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	PRIMARY KEY(id_curs,id_locatie)
);
GO